# Travel Agent Configuration

# Model settings
model:
  name: "gemini-pro"
  temperature: 0.7
  max_output_tokens: 2048

# Search settings
search:
  max_results: 5
  search_depth: "advanced"  # basic, advanced
  
# Default preferences
defaults:
  currency: "VND"
  max_budget_vnd: 100000000
  min_days: 1
  max_days: 30
